### ISSUE TITLE
Difficulty with joystick input

### ISSUE THREAD

**Issue by Ophidios** [AltimorTASDK/altinput#3]
Everything is working great except for the joystick input - I see the entry in the tgm3.cfg for "// Configured for Hori Real Arcade Pro VX SA KAI", however even if I modify the button numbers to match my input device, it doesn't seem to accept any input at all. I've tried with an Xbox 360, Xbox One, and HORI Rap N controllers without any luck.

Is there a setting elsewhere or something else that needs configured/compiled? How does it actually know which input device to poll from?

**Comment by AltimorTASDK** [comment]
What input device?

The required name in the config should match with what's displayed in joy.cpl.

**Comment by Ophidios** [comment]
Well, in my case I was trying to use a Rap N. So I would just change the text after “// Configured for” to the descriptor shown in joy.cpl?

**Comment by AltimorTASDK** [comment]
`//` marks the line as a comment, so changing that line won't do anything. It's only there to inform people who read the config. You need to change the name before the block with the config for the device, e.g.

```
"My Device Name (from joy.cpl)"
{
    // settings for the device go here
}
```

**Comment by Ophidios** [comment]
Gotcha - the default config in the ZIP file from github doesn't have any entry for that, so I think that was what was hanging me up. So just to clarify, this should be correct?

> joystick
"Controller (RAP.N4)"
{
        // settings omitted to save space
}`

I still don't get any input when doing it this way, unfortunately. I've tried it with two other controllers as well (Xbox 360 and Xbox One, with the appropriate button settings), and two different computers. I've tried using the name as it appears in joy.cpl as well as the bus reported device description (another post I saw online said to try this) and in both cases for all controllers the input still doesn't seem to take.

**Comment by Ophidios** [comment]
I figured it out by referencing an older release found on another site. Despite how the tgm3.cfg is setup in the latest release build, it appears it has to be nested:

<pre><code>joystick
{
	"Controller (RAP.N4)"
	{
		player		1
		deadzone	0.5	// 0.0 to 1.0
	
		// Axes
		up_down		-1
		left_right	-1
	
		// Buttons
		up		-1
		down		-1
		left		-1
		right		-1
	
		// Hat switch
		hat_up		1
		hat_down	5
		hat_left	7
		hat_right	3
	
		A		1
		B		3
		C		4
		D		6
	
		start	8
	}
}</code></pre>

The buttons don't match those shown in joy.cpl, but that I can figure out by trial and error.
